import java.io.File;
import java.io.PrintWriter;
import java.util.regex.Pattern;

/**
 * The compilation engine gets its input from a {@link JackTokenizer} and emits its output to an output file. The output
 * is generated by a series of <code>compile</code><i>xxx</i> routines, each designed to handle the compilation of a
 * specific Jack language construct <i>xxx</i>. The contract between routines is that each <code>compile</code><i>xxx</i>
 * routine should get from the input, and handle, all the tokens that make up <i>xxx</i>, advance the tokenizer exactly
 * beyond these tokens, and output the parsing of <i>xxx</i>. As a rule, each <code>compile</code><i>xxx</i> is called
 * only if the current token is <i>xxx</i>.
 *
 * @author Maarten Derks
 */
class CompilationEngine {

    private final JackTokenizer jt;
    private final SymbolTable cst, sst;
    private final VMWriter vmw;

    private final String integerConstant = "^(0|[1-9]\\d*)$";
    private final String stringConstant = "\".*?\"";
    private final String identifier = "[a-zA-Z_][a-zA-Z0-9_]*";
    private final String className = identifier;
    private final String varName = identifier;
    private final String subroutineName = identifier;
    private final String op = "\\+|-|\\*|/|&|\\||<|>|=";
    private final String unaryOp = "-|~";
    private final String keywordConstant = "true|false|null|this";

    /**
     * Creates a new compilation engine with the given input and output.
     *
     * @param in  Input stream/file
     * @param out Output stream/file
     */
    CompilationEngine(File in, File out) throws Exception {
        jt = new JackTokenizer(in);
        vmw = new VMWriter(out);
        cst = new SymbolTable();
        sst = new SymbolTable();
        jt.advance();
    }

    /**
     * Compiles a complete class.
     */
    void compileClass() {
        process("class");
        process(className);
        process("{");
        while (jt.tokenType() == TokenType.KEYWORD &&
                (jt.keyWord() == Keyword.STATIC || jt.keyWord() == Keyword.FIELD)) {
            compileClassVarDec();
        }
        while (jt.tokenType() == TokenType.KEYWORD &&
                (jt.keyWord() == Keyword.CONSTRUCTOR || jt.keyWord() == Keyword.FUNCTION || jt.keyWord() == Keyword.METHOD)) {
            compileSubroutine();
        }
        process("}");
        vmw.close();
    }

    /**
     * Compiles a static variable declaration, or a field declaration.
     */
    private void compileClassVarDec() {
        String kind = process("static|field");
        String type = jt.identifier();
        jt.advance();
        cst.define(jt.identifier(), type, Kind.valueOf(kind.toUpperCase()));
        jt.advance();
        while (jt.tokenType() == TokenType.SYMBOL && jt.symbol() == ',') {
            process(",");
            cst.define(jt.identifier(), type, Kind.valueOf(kind.toUpperCase()));
            jt.advance();
        }
        process(";");
    }

    /**
     * Compiles a complete method, function, or constructor.
     */
    private void compileSubroutine() {
        sst.reset();
        process("constructor|function|method");
        process("void|int|char|boolean|" + className);
        process(subroutineName);
        process("(");
        compileParameterList();
        process(")");
        compileSubroutineBody();
    }

    /**
     * Compiles a (possibly empty) parameter list. Does not handle the enclosing parentheses tokens ( and ).
     */
    private void compileParameterList() {
        if (jt.tokenType() == TokenType.KEYWORD && (jt.keyWord() == Keyword.INT || jt.keyWord() == Keyword.BOOLEAN)) {
            String type = jt.identifier();
            jt.advance();
            sst.define(jt.identifier(), type, Kind.ARG);
            jt.advance();
        }
        while (jt.tokenType() == TokenType.SYMBOL && jt.symbol() == ',') {
            process(",");
            String type = jt.identifier();
            jt.advance();
            sst.define(jt.identifier(), type, Kind.ARG);
            jt.advance();
        }
    }

    /**
     * Compiles a subroutine's body.
     */
    private void compileSubroutineBody() {
        process("{");
        while (jt.tokenType() == TokenType.KEYWORD && jt.keyWord() == Keyword.VAR) {
            compileVarDec();
        }
        compileStatements();
        process("}");
    }

    /**
     * Compiles a <code>var</code> declaration.
     */
    private void compileVarDec() {
        process("var");
        String type = jt.identifier();
        jt.advance();
        sst.define(jt.identifier(), type, Kind.VAR);
        jt.advance();
        while (jt.tokenType() == TokenType.SYMBOL && jt.symbol() == ',') {
            process(",");
            sst.define(jt.identifier(), type, Kind.VAR);
            jt.advance();
        }
        process(";");
    }

    /**
     * Compiles a sequence of statements. Does not handle the enclosing curly bracket tokens { and }.
     */
    private void compileStatements() {
        while (jt.tokenType() == TokenType.KEYWORD && (jt.keyWord() == Keyword.LET || jt.keyWord() == Keyword.IF || jt.keyWord() == Keyword.WHILE || jt.keyWord() == Keyword.DO || jt.keyWord() == Keyword.RETURN)) {
            switch (jt.keyWord()) {
                case LET: compileLet(); break;
                case IF: compileIf(); break;
                case WHILE: compileWhile(); break;
                case DO: compileDo(); break;
                case RETURN: compileReturn(); break;
            }
        }
    }

    /**
     * Compiles a <code>let</code> statement.
     */
    private void compileLet() {
        process("let");
        process(varName);
        if (jt.tokenType() == TokenType.SYMBOL && jt.symbol() == '[') {
            process("[");
            compileExpression();
            process("]");
        }
        process("=");
        compileExpression();
        process(";");
    }

    /**
     * Compiles an <code>if</code> statement, possibly with a trailing <code>else</code> clause.
     */
    private void compileIf() {
        process("if");
        process("(");
        compileExpression();
        process(")");
        process("{");
        compileStatements();
        process("}");
        if (jt.tokenType() == TokenType.KEYWORD && jt.keyWord() == Keyword.ELSE) {
            process("else");
            process("{");
            compileStatements();
            process("}");
        }
    }

    /**
     * Compiles a <code>while</code> statement.
     */
    private void compileWhile() {
        process("while");
        process("(");
        compileExpression();
        process(")");
        process("{");
        compileStatements();
        process("}");
    }

    /**
     * Compiles a <code>do</code> statement.
     */
    private void compileDo() {
        process("do");
        process(identifier);
        if (jt.tokenType() == TokenType.SYMBOL && jt.symbol() == '.') {
            process(".");
            process(subroutineName);
        }
        process("(");
        compileExpressionList();
        process(")");
        process(";");
    }

    /**
     * Compiles a <code>return</code> statement.
     */
    private void compileReturn() {
        process("return");
        if (jt.tokenType() == TokenType.SYMBOL && jt.symbol() == ';') {
            process(";");
        } else {
            compileExpression();
            process(";");
        }
    }

    /**
     * Compiles an expression.
     */
    private void compileExpression() {
        compileTerm();
        while (jt.tokenType() == TokenType.SYMBOL && (
                jt.symbol() == '+' ||
                        jt.symbol() == '-' ||
                        jt.symbol() == '*' ||
                        jt.symbol() == '/' ||
                        jt.symbol() == '&' ||
                        jt.symbol() == '|' ||
                        jt.symbol() == '<' ||
                        jt.symbol() == '>' ||
                        jt.symbol() == '='
        )) {
            process(op);
            compileTerm();
        }
    }

    /**
     * Compiles a (possibly empty) comma-separated list of expressions.
     *
     * @return  the number of expressions in the list
     */
    private int compileExpressionList() {
        int numberOfExpressions = 0;
        while (jt.symbol() != ')') {
            compileExpression();
            numberOfExpressions++;
            while (jt.tokenType() == TokenType.SYMBOL && jt.symbol() == ',') {
                process(",");
                compileExpression();
                numberOfExpressions++;
            }
        }
        return numberOfExpressions;
    }

    /**
     * Compiles a <i>term</i>. If the current token is an <i>identifier</i>, the routine must distinguish between a
     * <i>variable</i>, an <i>array entry</i>, or a <i>subroutine call</i>. A single look-ahead token, which may be one
     * of "[", "(", or ".", suffices to distinguish between the possibilities. Any other token is not part of this term
     * and should not be advanced over.
     */
    private void compileTerm() {
        switch (jt.tokenType()) {
            case INT_CONST:
                process(integerConstant);
                break;
            case STRING_CONST:
                process(stringConstant);
                break;
            case KEYWORD:
                process(keywordConstant);
                break;
            case IDENTIFIER:
                process(varName);
                if (jt.tokenType() == TokenType.SYMBOL && jt.symbol() == '[') {
                    process("[");
                    compileExpression();
                    process("]");
                }
                if (jt.tokenType() == TokenType.SYMBOL && jt.symbol() == '.') {
                    process(".");
                    process(subroutineName);
                    process("(");
                    compileExpressionList();
                    process(")");
                }
                break;
            case SYMBOL:
                switch (jt.symbol()) {
                    case '(':
                        process("(");
                        compileExpression();
                        process(")");
                        break;
                    case '-':
                    case '~':
                        process(unaryOp);
                        compileTerm();
                        break;
                }
                break;
        }
    }

    /**
     * A helper routine that handles the current token, and advances to get the next token.
     *
     * @param str
     */
    private String process(String str) {
        String token = jt.identifier();
        switch (str) {
            case "{":
            case "(":
            case ")":
            case "[":
                str = "\\".concat(str);
        }
        if (Pattern.matches(str, token));
        if (jt.hasMoreTokens()) jt.advance();
        return token;
    }
}